services:
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - logs:/app/pkg/logging/logs
      - ./server/internal/cfg/config.yaml:/app/internal/cfg/config.yaml
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: localhost
      BACKEND_PORT: 8080
    depends_on:
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
  logs: