listen:
  bindIp: 127.0.0.1
  port: 8080
database:
  host: localhost
  port: 5432
  userName: postgres
  password: "00000000"
  dbName: chatTest
auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 720h # 30 days
  secretKey: "superSecretKey"