listen:
  bindIp: 0.0.0.0
  port: 8080
database:
  host: db
  port: 5432
  userName: postgres
  password: "00000000"
  dbName: chatTest
auth:
  accessTokenTTL: 15m
  refreshTokenTTL: 720h # 30 days
  secretKey: "superSecretKey"